
# -----------  Agents  -----------

# Key password: qwe123
[[agents]]
id = "test_agent1"
name = "HoloTester1"
public_address = "HcSCJvN8k9fKMw3nm55JcqIa7WSguf83gX7OZYOuGEsos89siX5kt4JkoMvbcii"
key_file = "./agent1-key.txt"

# -----------  DNA  -----------

[[dnas]]
id = "event_dna"
file = "dna/logistics.dna.json"
hash = "Qm328wyq38924y"

[[instances]]
id = "logistics_test_agent1"
dna = "event_dna"
agent = "test_agent1"

[instances.logger]
type = "simple"
file = "app_spec.log"

[instances.storage]
type = "file"
path = "tmp-storage-agent1"

[[interfaces]]
id = "websocket_interface"

[interfaces.driver]
type = "websocket"
port = 3000

[[interfaces.instances]]
id = "logistics_test_agent1"

# -----------  UI  -----------

[[ui_bundles]]
id = "main"
root_dir = "./ui-agent1"
hash = "Qmjhoi"

[[ui_interfaces]]
id = "ui-interface"
bundle = "main"
port = 8800
dna_interface = "websocket_interface"

# -----------  Networking  -----------
[network]
n3h_path = "/Users/kristoferlund/hc/n3h-0.0.6-alpha1"
n3h_persistence_path = "/tmp"
bootstrap_nodes = []

# ⚠️ Set absolute path to n3h before starting first time.