
# -----------  Agents  -----------


# Key password: qwe123
[[agents]]
id = "test_agent1"
name = "HoloTester1"
public_address = "HcSCJvN8k9fKMw3nm55JcqIa7WSguf83gX7OZYOuGEsos89siX5kt4JkoMvbcii"
key_file = "./agent1-key.txt"

# -----------  DNA  -----------

[[dnas]]
id = "event_dna"
file = "dna/logistics.dna.json"
hash = "Qm328wyq38924y"

[[instances]]
id = "logistics"
dna = "event_dna"
agent = "test_agent1"

[instances.logger]
type = "simple"
file = "app_spec.log"

[instances.storage]
type = "memory"

[[interfaces]]
id = "websocket_interface"

[interfaces.driver]
type = "websocket"
port = 3000

[[interfaces.instances]]
id = "logistics"

